name: Release Check

on:
    push:
        branches:
            - main

jobs:
    changes:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: read
        outputs:
            backend: ${{ steps.filter.outputs.backend }}
            frontend: ${{ steps.filter.outputs.frontend }}
            extra: ${{ steps.filter.outputs.extra }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Detect Changes
              id: filter
              uses: dorny/paths-filter@v3
              with:
                  filters: |
                      backend:
                        - 'apps/backend/**'
                        - 'yarn.lock'
                      frontend:
                        - 'apps/frontend/**'
                        - 'yarn.lock'
                      extra:
                        - 'apps/extra/**'
                        - 'yarn.lock'

    backend:
        runs-on: ubuntu-latest
        needs: changes
        if: ${{ needs.changes.outputs.backend == 'true' }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Backend Release
              run: |
                  echo "Backend release"

    frontend:
        runs-on: ubuntu-latest
        needs: changes
        if: ${{ needs.changes.outputs.frontend == 'true' }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Frontend Release
              run: |
                  echo "Frontend release"

    extra:
        runs-on: ubuntu-latest
        needs: changes
        if: ${{ needs.changes.outputs.extra == 'true' }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Extra Release
              run: |
                  echo "Extra release"
